name: tusachdart
version: 0.0.1
description: A web app built using polymer.dart.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  intl: any
  paper_elements: '>=0.7.0'
  polymer: '>=0.16.0 <0.17.0'
  route_hierarchical: any
transformers:
- polymer:
    entry_points: web/index.html
